version: '2'
services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:${KAFKA_SECURITY_PROTOCOL},${KAFKA_SECURITY_PROTOCOL}:${KAFKA_SECURITY_PROTOCOL}
      KAFKA_LISTENERS: ${KAFKA_SECURITY_PROTOCOL}://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_SECURITY_PROTOCOL}://localhost:9092
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
